// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_LOGINPACKET_PACKETS_H_
#define FLATBUFFERS_GENERATED_LOGINPACKET_PACKETS_H_

#include "../flatbuffers/flatbuffers.h"

namespace Packets {

struct LoginPacket;

struct LoginPacket FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_NAME = 4
  };
  const flatbuffers::String *name() const { return GetPointer<const flatbuffers::String *>(VT_NAME); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           verifier.EndTable();
  }
};

struct LoginPacketBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) { fbb_.AddOffset(LoginPacket::VT_NAME, name); }
  LoginPacketBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  LoginPacketBuilder &operator=(const LoginPacketBuilder &);
  flatbuffers::Offset<LoginPacket> Finish() {
    auto o = flatbuffers::Offset<LoginPacket>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<LoginPacket> CreateLoginPacket(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0) {
  LoginPacketBuilder builder_(_fbb);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<LoginPacket> CreateLoginPacketDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr) {
  return CreateLoginPacket(_fbb, name ? _fbb.CreateString(name) : 0);
}

inline const Packets::LoginPacket *GetLoginPacket(const void *buf) { return flatbuffers::GetRoot<Packets::LoginPacket>(buf); }

inline bool VerifyLoginPacketBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<Packets::LoginPacket>(nullptr); }

inline void FinishLoginPacketBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<Packets::LoginPacket> root) { fbb.Finish(root); }

}  // namespace Packets

#endif  // FLATBUFFERS_GENERATED_LOGINPACKET_PACKETS_H_
